"""Source-led classroom HUB preparation. Remake branches are planned, never fabricated."""
from copy import deepcopy
DATE='2026-09-26'
REV='r6-preclass-20260926'
def bi(z,e):return [z,e]
def req(id,title,body,accept):return {'id':id,'title':title,'detail':body,'acceptance':accept}
def event(id,date,title,summary,result,source,tech):return {'id':id,'date':date,'title':title,'summary':summary,'brief':summary,'tool':bi('课堂需求 → 实现 → 反馈 → 修订；此处为已有记录归纳。','Class requirements → implementation → feedback → revision; reconstructed from existing records.'),'tech':tech,'result':result,'source':source,'status':'done'}
def learn(title,practice,knowledge,expression,level=None):return {'title':title,'practice':practice,'knowledge':knowledge,'expression':expression,'level':level or bi('来自仓库课堂纪要的复盘；不视为完整逐字稿或独立掌握证明。','Retrospective from repository lesson notes, not a complete transcript or proof of independent mastery.')}
COMMON_TESTS=[
 bi('首次进入能理解目标并完成核心动作；不靠调试开关跳过正常流程。','A first-time player understands the goal and performs the core actions without debug shortcuts.'),
 bi('iPad无键盘、键盘无鼠标两种输入分别验收；拖出、取消、旋转后不粘键。','Verify keyboard-free iPad and mouse-free keyboard play; release, cancellation and rotation must not leave movement stuck.'),
 bi('中英切换按钮常驻，中文显示English、英文显示中文；不丢进度与表单内容。','Persistent target-language button: English in Chinese, 中文 in English; preserve progress and form content.'),
 bi('直接单机试玩、返回本作品HUB、独立存档与可重开；不能影响旧版或另一候选。','Direct solo play, return to this HUB, independent saves and restart; do not alter the baseline or other candidate.'),
 bi('源文件、实际用量或有依据的估算、测试结果及失败记录一并交回；不能把历史报告当本次测试。','Return source, metered usage or explicit estimates, tests and failures; do not reuse historical reports as new acceptance.'),
 bi('最终正常流程与实际设备测试通过后才冻结MVP；本轮不自动进入完整资产、销售和长期运营。','Freeze the MVP only after normal-path/device acceptance; do not silently start full asset production, sales or long-term operations.')]
PROJECTS={
'aidan':{
 'repo':'aidan-minecraft-web','name':'Aidan','people_names':['Aidan'],'theme':'forest','budget':50,
 'title':bi('Aidan 的魔法方块世界','Aidan’s Magic Block World'),
 'heroTitle':bi('魔法，真的改变世界<br><em>Aidan · 两路重制准备</em>','Magic that changes the world<br><em>Aidan · remake preparation</em>'),
 'intro':bi('从自由建造，走到火焰、水与食物循环，再走进昼夜生态。这次先保存已经想清楚的规则，为 Opus 和 Astra 准备同一份重制需求；新版尚未制作。','From free building to fire, water and food, then day/night ecology. Preserve the rules already developed and prepare one shared brief for Opus and Astra. The remakes have not been built.'),
 'source_head':'2b22154','legacy_name':bi('现有基线 · 魔法与昼夜生态版','Existing baseline · magic and day/night ecology'),
 'legacy_tag':'legacy-daynight','legacy_release':bi('9月19日旧版，供课前试玩对照','19 September baseline for pre-class comparison'),
 'source_paths':['DEVLOG.md','README.md','src/magic.js','src/creatures.js','src/daynight.js','src/monsters.js','src/walk.js','src/storage.js'],
 'requirements':[
 req('A-01',bi('魔法要改变世界，不只是漂亮','Magic must change the world, not just look pretty'),bi('保留火球点燃可燃物、火遇水熄灭产生蒸汽；火会造成危险，有明确反馈。','Retain fireballs igniting flammable blocks, water extinguishing fire into steam, and readable danger/feedback.'),bi('正常操作分别验证烧木、遇水、站在火边受伤和恢复。','Use normal actions to test burning wood, water contact, fire damage and recovery.')),
 req('A-02',bi('抓鱼 → 烤鱼 → 吃鱼','Catch → cook → eat'),bi('水里要有看得见且可互动的生命；抓鱼、放下、烤熟、拾取、食用与生命/移动效果互相连接。','Water needs visible interactive life; catching, placing, cooking, collecting and eating connect to health/movement effects.'),bi('从零获得一条鱼，用正常操作走完整条食物循环。','Obtain a fish from scratch and complete the food loop through normal play.')),
 req('A-03',bi('昼夜有区别，但动物不消失','Day and night differ, without deleting animals'),bi('太阳白天、月亮夜间；晚上出现怪物，魔法能打怪；鱼与小鸡保持存在，浆果可采集。','Sun by day, moon by night; monsters appear at night and respond to magic; fish/chickens persist and berries are collectable.'),bi('切换昼夜确认日月、怪物、动物与资源各自的状态；不把白天清怪误写成删掉所有生物。','Switch day/night and verify celestial, monster, animal and resource states separately.')),
 req('A-04',bi('保留自由创造与可靠存档','Keep creative building and dependable saves'),bi('保留飞行、挖掘、放置、方块库及保存/导入导出。先复现已有目标，不额外承诺所有Minecraft机制。','Retain flight, mining, placement, inventory and save/import/export. Recreate established goals, not every Minecraft mechanic.'),bi('搭一个小结构、保存、刷新、导出再导入，验证没有误删旧版存档。','Build a small structure, save, reload and export/import without deleting baseline saves.'))],
 'scope_out':bi('不把“挖穿基岩”当作新增玩法；不无限复制Minecraft；不擅加多人云服、商城或完整美术资产生产。','No bedrock-digging feature for its own sake, unlimited Minecraft parity, unrequested cloud multiplayer, store or full asset production.'),
 'class_questions':[
 bi('让魔法改变世界的哪个瞬间最值得留下？请演示一次。','Which moment of magic changing the world matters most? Demonstrate it.'),
 bi('新版第一分钟希望玩家完成什么小目标？不要只说“更好玩”。','What small goal should a player complete in minute one? Be more specific than “more fun”.'),
 bi('火焰、食物、夜晚怪物之间，哪个选择应该让玩家认真想一下？','Which choice between fire, food and night monsters should require thought?')],
 'journey':[
 event('initial','2026-09-12',bi('从想做Minecraft，收敛到创造与分享','From Minecraft inspiration to creation and sharing'),bi('原方向是飞行建造、挖掘放置、方块库与建筑存档。','The original scope was flying/building, mining/placing, inventory and saved creations.'),bi('留下可玩的体素原型；历史帧率自述不作为本轮实测结论。','An operable voxel prototype; historical frame-rate claims are not fresh measurements.'),'A-HISTORY',bi('程序化像素图集、隐藏面剔除、AABB碰撞和JSON存档。','Procedural texture atlas, face culling, AABB collision and JSON saves.')),
 event('input','2026-09-12',bi('实际设备改变输入需求','Real devices change input requirements'),bi('记录中有iPad打不开、没有带鼠标两项反馈。','Notes report trouble opening on iPad and a missing mouse.'),bi('补触屏与纯键盘操控；局域网静态分发与多人同步不是一回事。','Touch and mouse-free keyboard controls added; static LAN delivery is not multiplayer synchronization.'),'A-HISTORY',bi('将开发服务器与成品静态资源分开，按输入设备验证。','Separate development server and production static assets; test each input device.')),
 event('magic','2026-09-19',bi('水里什么都没有 → 魔法食物循环','Empty water → magic and food loop'),bi('Aidan喜欢飞行和创造，但水域缺少内容；讨论后放弃无目标的挖穿基岩。','Aidan liked flight/creation but found water empty; purposeless bedrock digging was dropped.'),bi('加入火焰、水下鱼与抓烤吃循环。仓库日志称27项冒烟通过；原测试报告未附在该仓库。','Added fire, fish and catch/cook/eat. The log claims 27 smoke checks; the raw report is not in this repository.'),'A-HISTORY',bi('粒子与小步长碰撞、燃烧队列、蒸汽反馈和资源状态转换。','Particles/substep collisions, burning queues, steam feedback and resource-state changes.')),
 event('ecology','2026-09-19',bi('日月交替、怪物和不消失的动物','Day/night, monsters and persistent animals'),bi('补日月规律、夜间威胁、浆果与跟随小鸡，动物不随怪物清理。','Add celestial rules, night threats, berries and following chickens; ordinary animals survive monster cleanup.'),bi('形成当前基线；日志中的63项测试合计作为历史报告，不冒称本轮重跑。','Current baseline established; the reported 63 checks remain historical, not a new rerun.'),'A-HISTORY',bi('按脚下方块与一格台阶判定走路，替换把树冠当地面的高度判断。','Use foot-level blocks and one-block steps instead of treating treetops as walkable ground.'))],
 'learning':[
 learn(bi('把“不够好”说成可实现的缺口','Turn “not good enough” into a concrete gap'),bi('“水里什么都没有”引出了水下生命和互动，而非盲目加方块。','“There is nothing in the water” led to aquatic life/interactions rather than more block types.'),bi('需求应描述缺失体验及可观察结果。','Requirements describe a missing experience and observable result.'),bi('我在……看到了……；我希望能做……，完成后应该看到……。','At … I observed …; I want to do … and then see ….')),
 learn(bi('先问用途，再决定功能','Ask its purpose before adding a feature'),bi('讨论“挖穿基岩”时发现没有形成玩法目标，选择不做。','Bedrock digging had no gameplay purpose and was excluded.'),bi('范围控制：功能数量不等于玩法价值。','Scope control: feature count is not gameplay value.'),bi('这个功能让玩家做什么决定？不用它，会失去什么体验？','What decision does this feature create? What experience is lost without it?')),
 learn(bi('资源状态接成闭环','Connect resource states into a loop'),bi('鱼从水里被抓到、放下、烤熟、拾取并食用。','Fish move from water to catch, placement, cooking, pickup and consumption.'),bi('状态转换与反馈必须一致；不能按钮变化却没有真实资源变化。','State transitions and feedback must agree; UI changes are not resource changes.'),bi('先得到A，把A通过B变成C；C如何帮助下一轮行动？','Obtain A, use B to turn it into C; how does C help the next action?')),
 learn(bi('区分地形高度和可走的地面','Terrain height differs from walkable ground'),bi('代码记录树下生物会把树冠当脚下地面，后来修正行走判定。','The recorded bug treated treetops as ground beneath creatures; walking checks were revised.'),bi('边界条件、碰撞与导航；技术解释来自代码，不冒称课堂已全部教完。','Boundary conditions, collisions and navigation; this explanation comes from code, not a claim of full classroom mastery.'),bi('在什么位置会卡住？脚下是哪种方块？修完怎样证明没有回归？','Where does it get stuck, what block is underfoot, and how do we retest?'))],
 'issues':[
 ['A-UI',bi('存档与输入边界仍需新版验证','Saves and input boundaries need remake testing'),bi('源文档给出多种键位，个别按键承担多个语义；重制时要明确优先级，不直接照抄。','Historical controls reuse some keys for multiple meanings; define precedence instead of copying blindly.'),bi('重制验收项','Remake acceptance item')],
 ['A-EVIDENCE',bi('旧报告和本轮证据分开','Keep historical reports separate'),bi('日志称有27/36项自动检查，但原始结果和截图不在该仓库；本轮只核验展示与旧版启动，不自动宣称全面通过。','Logs claim 27/36 checks, but their raw reports/screenshots are absent; this pass only verifies HUB and baseline startup.'),bi('保留证据缺口','Evidence gap retained')]],
 'rating':{'points':[25,18,12,10,7],'reasons':[
 bi('建造、魔法、食物与昼夜形成有联系的互动；首分钟目标和成长动机仍可加强。','Building, magic, food and day/night connect; first-minute goals and progression motivation need strengthening.'),bi('已实现触屏与纯键盘分支；无完整新设备验收，复杂操作还需清晰引导。','Touch and keyboard paths exist; comprehensive current-device acceptance and clearer control guidance remain.'),bi('源码与修复日志可核对，但原测试原始回执不齐，不能按历史宣传打满分。','Source and repair logs are inspectable, but raw historical test evidence is incomplete.'),bi('程序化世界和即时声画反馈可支撑MVP，正式故事与资产仍未制作。','Procedural visuals/feedback support an MVP; production story/assets remain unbuilt.'),bi('可保存建筑且Git里保留迭代，重制需独立存档和版本登记。','Saved creations and Git iterations exist; remakes need isolated saves/version registration.')],
 'strength':bi('“魔法改变世界”和抓烤吃循环具有作品自己的方向。','World-changing magic and the catch/cook/eat loop give the work its own direction.'),'risk':bi('有功能不等于完整游戏设计；旧测试报告缺失，不能夸成全部实机通过。','Features do not equal complete game design; missing reports prevent full-device claims.'),'next_test':bi('按正常流程建造、存取、抓烤吃、昼夜打怪；在真实iPad验证操作和反馈。','Test normal building/saves, fish cooking, day/night combat and real-iPad controls/feedback.')},
 'budget_items':[
 [bi('9/12 创建、输入与分发修订','12 Sep creation, input and delivery revisions'),6,3,10,bi('无原Token账单，按记录中的范围给工具等值估算。','No metered token bill; scope-based tool-equivalent estimate.')],
 [bi('9/19 魔法、食物与昼夜生态','19 Sep magic, food and ecology'),8,4,16,bi('按两个有源码提交的扩展阶段估算，不按旧帧率宣传估值。','Estimate for two source-backed expansion stages, not historical performance claims.')],
 [bi('本次HUB回收与适配','This HUB recovery/adaptation'),4,2,6,bi('本次整理、展示、分支入口和检查的工具等值预估。','Tool-equivalent estimate for this recovery, UI, branch entries and checks.')]],
 'reserve_each':10,
 'human_tasks':[[bi('需求与核心循环','Requirements and loop'),3,5],[bi('体素世界与互动','Voxel world and interactions'),10,18],[bi('输入与保存','Input and persistence'),5,9],[bi('魔法、生态与昼夜','Magic, ecology and day/night'),8,14],[bi('检查与作品档案','Testing and project record'),5,9]],
 'history_versions':[['d80d7dc','2026-09-12',bi('创造与输入基线','Creative/input baseline')],['4a57829','2026-09-19',bi('魔法与抓烤吃','Magic and catch/cook/eat')],['2b22154','2026-09-19',bi('昼夜与地面生态','Day/night and ground ecology')]]
},
'hiro-brynne':{
 'repo':'hiro-brynne-zombie-dungeon','name':'Hiro · Brynne','people_names':['Hiro','Brynne'],'theme':'space','budget':100,
 'title':bi('Hiro 与 Brynne：僵尸地牢','Hiro & Brynne: Zombie Dungeon'),
 'heroTitle':bi('地牢里，需要真正的选择<br><em>Hiro · Brynne · 两路重制准备</em>','A dungeon needs meaningful choices<br><em>Hiro · Brynne · remake preparation</em>'),
 'intro':bi('现有作品已能找钥匙、开地穴、击败僵尸王、带宝藏逃生。重制不只把地图拉长，而是把孩子提出的节奏、选择、互动与合作重新组织；Opus 与 Astra 尚未开工。','The baseline has keys, crypt gate, Zombie King, treasure and escape. The remake should organize pacing, choices, interactions and cooperation—not only extend the map. Opus and Astra have not started.'),
 'source_head':'c9724ac','legacy_name':bi('现有基线 · Zombie Dungeon V2.1','Existing baseline · Zombie Dungeon V2.1'),
 'legacy_tag':'legacy-v21','legacy_release':bi('9月19日单机版，保留LAN源码','19 September solo release, LAN source retained'),
 'source_paths':['index.html','public/singleplayer.html','public/js/localSocket.js','public/js/game.js','server.js'],
 'requirements':[
 req('H-01',bi('保留明确的地牢冒险闭环','Keep a clear dungeon-adventure loop'),bi('保留第一人称、僵尸追击、战斗、剑、绷带、钥匙、地穴门、Boss、宝藏与逃生。','Retain first-person exploration, zombie pursuit, combat, sword, bandages, key, crypt gate, boss, treasure and escape.'),bi('从开局正常找到钥匙并完成Boss与逃生；死亡与重开也必须可恢复。','Normally find the key, defeat the boss and escape; verify defeat/restart recovery too.')),
 req('H-02',bi('按真实反馈修操作与节奏','Repair controls and pacing from actual feedback'),bi('已有反馈包括迷宫太短、可互动少、朝向不对、速度太快；保留打击红色反馈与胜利时刻。','Existing feedback names short maze, too few interactions, wrong facing and excessive speed; retain hit feedback and the victory moment.'),bi('使用同一设备比较移动、敌人朝向、攻击反馈与首次任务理解。','Compare movement, enemy facing, hit feedback and first-goal comprehension on the same device.')),
 req('H-03',bi('合作要有作用，而非只在同一地图','Cooperation must matter beyond a shared map'),bi('双人iPad合作是既有目标。新版先提出少量能被验证的合作选择；救援、分工或共享资源仍需课堂选定，不全量自动加入。','Two-iPad cooperation is an existing goal. Propose a small testable cooperative choice; rescue, roles or shared resources remain class decisions, not automatic additions.'),bi('说明两个人怎样互相影响结果；单人模式仍能独立完成核心流程。','Explain how two players affect the outcome while solo can still complete the core loop.')),
 req('H-04',bi('先改善决策与引导，再做完整资产','Improve decisions and guidance before full assets'),bi('旧Hub指出重复“走路然后打怪”的问题。暗氛围、环境声和音乐是方向，但本阶段只需足够支持MVP，不擅自进入完整音画制作。','The old HUB identifies repetitive walk-and-fight play. Dark atmosphere/music/environment sound are directions; only MVP-supporting presentation belongs in this pass.'),bi('玩家能指出一个有代价的选择及其反馈；正式故事、视觉、音乐、音效、配音留在第二阶段。','A player can identify one meaningful trade-off and feedback; full story/art/music/sound/voice belong to phase 2.'))],
 'scope_out':bi('不自动加入全部roguelike升级、随机地图、商店或所有合作机制；不把现有LAN共玩宣称为已部署公网联机。','Do not automatically add every roguelike upgrade, random map, shop or co-op mechanic; existing LAN play is not a deployed public multiplayer service.'),
 'class_questions':[
 bi('玩家每隔一小段时间，应在“战斗、绕路、消耗绷带、帮助伙伴”中做什么选择？','What choices should recur between fighting, taking a detour, spending bandages and helping a teammate?'),
 bi('双人玩应该在哪一个动作上明显优于单人？先选一个机制。','Which one action should make co-op meaningfully different from solo? Choose one mechanism first.'),
 bi('僵尸王应该考验躲避、时机还是配合？不只是增加血量。','Should the Zombie King test dodging, timing or coordination, rather than just more health?')],
 'journey':[
 event('brief','2026-09-19',bi('先做能玩的双人地牢','Start with a playable two-player dungeon'),bi('原Brief优先联机、移动、追击、战斗、胜负与道具，再做画面细节。','The original brief prioritized networking, movement, pursuit, combat, outcomes and items before visual detail.'),bi('形成课堂原型；未声称它已经是商业成品。','A classroom prototype, not a claimed commercial product.'),'H-OLDHUB',bi('Three.js客户端与Socket.IO共享状态。','Three.js clients with Socket.IO shared state.')),
 event('feedback','2026-09-19',bi('Brynne提出可定位的问题','Brynne identifies concrete problems'),bi('旧Hub记录迷宫短、互动少、角色/怪物朝向、速度和氛围反馈。','The prior HUB records feedback on maze length, interaction, facing, speed and atmosphere.'),bi('将体验意见转为修订输入，不把孩子的意见当作已经完成的功能。','Convert experience into revision requirements, not already-delivered features.'),'H-OLDHUB',bi('坐标朝向、速度平衡、灯光雾效与反馈。','Orientation, speed/balance, lighting/fog and feedback.')),
 event('v2','2026-09-19',bi('V2加地图内容与呈现','V2 expands content and presentation'),bi('旧记录说明扩地图、互动、声音、氛围并针对操作问题调整。','Historical notes describe more rooms/interactions/audio/atmosphere and targeted control fixes.'),bi('增加内容不等于增加有意义选择；不能只靠地图长度判定更好玩。','More content is not more meaningful choice; map length alone does not establish enjoyment.'),'H-OLDHUB',bi('调整关联规则而不只增物件。','Adjust connected rules rather than just adding objects.')),
 event('v21','2026-09-19',bi('V2.1单机完整流程','V2.1 full solo quest'),bi('钥匙→地穴门→僵尸王→宝藏→逃生，本机模拟既有事件接口。','Key → crypt gate → Zombie King → treasure → escape, with a local simulation of the event interface.'),bi('源代码与单机入口已归档；旧Hub的5.2/10可玩性评语保留为历史口径。','Source and solo entry archived; the old HUB’s 5.2/10 assessment remains a historical rating with its original scope.'),'H-SOLO',bi('本地事件适配与LAN服务分离，便于单机演示。','Separate local-event adaptation from the LAN server for solo demonstration.'))],
 'learning':[
 learn(bi('把体感说成可复现的现象','Turn feelings into reproducible observations'),bi('旧Hub记录Brynne说迷宫短、互动少、朝向反和速度太快。','The old HUB attributes short maze, limited interaction, reversed facing and excessive speed feedback to Brynne.'),bi('设备、动作、预期、实际四项比“修一下”更可执行。','Device, action, expectation and result are more actionable than “fix it”.'),bi('我在……做……；本来以为……，实际却……。','On … I did …; I expected … but saw ….')),
 learn(bi('区分完成清单和真正好玩','Distinguish a feature checklist from enjoyable play'),bi('道具、门、Boss和结局齐全，仍可能主要重复走路打怪。','Items, gate, boss and ending can all exist while most play is still walk-and-fight.'),bi('决策密度、节奏、奖励与复玩动机需要单独设计。','Choices, pacing, rewards and replay motivation need deliberate design.'),bi('这里让玩家在什么之间选择？选择不同，结果怎样不同？','What alternatives does the player choose between, and how do outcomes differ?')),
 learn(bi('共同地图不是完整合作机制','Sharing a map is not a full co-op mechanic'),bi('原型已经能共享地图；旧Hub明确合作规则深度不足。','The prototype shares a map; the old HUB identifies limited cooperative depth.'),bi('共享状态和合作设计分别验收；单机本地适配不代表互联网多人服务。','Test shared-state correctness separately from co-op design; local solo is not internet hosting.'),bi('我的动作怎样改变伙伴的情况？只靠自己能不能完成？','How does my action change my teammate’s situation? Can one person finish alone?')),
 learn(bi('一个参数会改变整个体验','One parameter can change the experience'),bi('速度、敌人追击、生命与奖励在同一个地牢里互相影响。','Speed, enemy pursuit, health and rewards interact in the same dungeon.'),bi('系统思维与控制变量；需要对照而不是一次改十项后猜原因。','Systems thinking and controlled comparison, not changing ten things and guessing.'),bi('只改这一项，再用同样路线测试，我们怎样知道它更好了？','Change one thing and test the same route: how will we know it improved?'))],
 'issues':[
 ['H-CHOICE',bi('选择与复玩深度不足','Limited choices and replay depth'),bi('旧Hub已指出固定地图、升级少、合作浅；重制先选少量核心机制，不把建议列表全部塞进MVP。','The prior HUB identifies fixed map, few upgrades and shallow co-op; select a few core changes rather than every idea.'),bi('共同Brief已列入','Included in shared brief')],
 ['H-INPUT',bi('朝向、速度和触屏需同设备比较','Facing, speed and touch need same-device comparison'),bi('历史中“针对问题调整”不等于已有当前实机验收。','Historical targeted fixes do not establish current physical-device acceptance.'),bi('重制验收项','Remake acceptance item')],
 ['H-NET',bi('原版LAN与公网联机分开','Distinguish LAN and public multiplayer'),bi('当前保留的公共入口是单机；公网房间与测评同步未在此作品部署，不能借用其他作品的状态。','The public baseline is solo; public rooms/review synchronization are not deployed for this work. Another project’s deployment status does not apply here.'),bi('未部署','Not deployed')]],
 'rating':{'points':[21,15,12,9,7],'reasons':[
 bi('已有钥匙、门、Boss与逃生闭环，玩法选择与成长仍不足。','Key/gate/boss/escape loop exists; choice and progression remain limited.'),bi('触屏与单机入口具备，原体验问题需要新版对照。','Touch and solo entry exist; previous experience issues need remake comparisons.'),bi('源码可读、历史有测试自述，但原完整报告未同仓保留。','Readable source and historical test claims exist, but the full raw report is not retained in the same repository.'),bi('气氛和打击反馈支持原型；房间变化和完整音画仍不足。','Atmosphere/hit feedback support the prototype; room variation and full audiovisual assets remain limited.'),bi('单机与LAN接口分离，版本可追溯；重制的发布证据尚不存在。','Solo/LAN interfaces are separated and history traceable; remake release evidence does not yet exist.')],
 'strength':bi('目标、战斗高潮和逃生结局能组成一个可演示流程。','Goal, combat climax and escape ending form a demonstrable loop.'),'risk':bi('清单完成并不等于有趣；历史5.2/10为旧口径，新AI分数仅评MVP功能与证据。','Checklist completion is not enjoyment; historical 5.2/10 uses a different rubric, while the new AI rating assesses MVP function/evidence.'),'next_test':bi('正常通关并记录选择、失败、恢复与两人协作差异，再评价重制候选。','Play through normally and record choices, failure/recovery and co-op differences before rating remake candidates.')},
 'budget_items':[
 [bi('原MVP、V2与V2.1修订','Original MVP, V2 and V2.1 revisions'),10,5,20,bi('没有原计量账单，依据旧Hub范围和两次提交作工具等值估算。','No original metered bill; tool-equivalent estimate from prior HUB scope and two commits.')],
 [bi('原家长学习HUB','Prior parent learning HUB'),2,1,4,bi('独立历史整理项，与游戏制作分开避免混算。','Historical documentation separate from game production.')],
 [bi('本次HUB适配与重制入口','This HUB adaptation and remake entries'),4,2,6,bi('工具等值规划估算，不是付款账单。','Tool-equivalent planning estimate, not an invoice.')]],
 'reserve_each':10,
 'human_tasks':[[bi('需求、任务与节奏','Requirements, quests and pacing'),4,7],[bi('场景、战斗与物品','Scene, combat and items'),10,18],[bi('输入与双人接口','Input and two-player interface'),6,10],[bi('单机、恢复与检查','Solo, recovery and checks'),6,10],[bi('HUB与学习记录','HUB and learning record'),4,7]],
 'history_versions':[['9085281','2026-09-19',bi('V2.1单机与LAN源码归档','V2.1 solo and LAN archive')],['c9724ac','2026-09-19',bi('家长学习Hub与历史评语','Parent learning HUB and historical assessment')]]
}}
