// Project-specific HUB checks; no model execution, student rooms or game logic changes.
const fs=require('fs'),path=require('path'),http=require('http'),crypto=require('crypto'),assert=require('node:assert/strict');const {chromium}=require(process.env.PLAYWRIGHT_PATH||'playwright');
const R=path.resolve(__dirname,'../..'),site=fs.existsSync(path.join(R,'docs/hub/project.json'))?path.join(R,'docs'):R,H=path.join(site,'hub'),P=Object.values(JSON.parse(fs.readFileSync(path.join(H,'project.json'))).projects)[0],repo=P.id==='aidan'?'aidan-minecraft-web':'hiro-brynne-zombie-dungeon',live=process.argv.includes('--live');
const report={revision:'r6-preclass-20260926',mode:live?'live':'local',project:P.id,scope:'Existing game startup/startup screenshot plus HUB, plans, language, diagrams, budgets and form checks. Not a remake implementation or full game acceptance.',checks:[],failures:[],started:new Date().toISOString()};let browser,server;
function check(name,value,detail){report.checks.push({name,status:value?'PASS':'FAIL',detail});if(!value)report.failures.push(name+(detail?': '+JSON.stringify(detail):''));}
const digest=b=>crypto.createHash('sha256').update(b).digest('hex');
(async()=>{try{
if(!live){server=http.createServer((req,res)=>{try{let u=decodeURIComponent(new URL(req.url,'http://localhost').pathname);if(!u.startsWith('/'+repo+'/'))throw Error();let f=path.resolve(site,u.slice(repo.length+2));if(f!==site&&!f.startsWith(site+path.sep))throw Error();if(fs.statSync(f).isDirectory())f=path.join(f,'index.html');res.setHeader('Content-Type',({'.html':'text/html;charset=utf-8','.js':'text/javascript','.css':'text/css','.json':'application/json','.svg':'image/svg+xml','.png':'image/png','.mmd':'text/plain;charset=utf-8','.txt':'text/plain;charset=utf-8'})[path.extname(f)]||'application/octet-stream');res.end(fs.readFileSync(f));}catch{res.writeHead(404).end('Not found');}});await new Promise(r=>server.listen(0,'127.0.0.1',r));}
const base=live?'https://sydneygemstone-sudo.github.io/'+repo+'/':`http://127.0.0.1:${server.address().port}/${repo}/`;
browser=await chromium.launch({headless:true,timeout:15000,...(process.env.CHROME_EXECUTABLE?{executablePath:process.env.CHROME_EXECUTABLE}:{}),args:['--use-angle=swiftshader','--enable-unsafe-swiftshader']});
// A few genuine rendered frames are sufficient for an honest baseline screenshot without measuring fps.
if(!live){const c=await browser.newContext({viewport:{width:1180,height:820},hasTouch:true,deviceScaleFactor:1});c.setDefaultTimeout(15000);const p=await c.newPage(),errs=[];p.on('pageerror',e=>errs.push(e.message));await p.goto(base+'play/',{waitUntil:'domcontentloaded'});await p.waitForSelector('#game');const frame=p.frames().find(f=>f!==p.mainFrame());assert(frame,'Baseline frame missing');await frame.waitForSelector('canvas');if(P.id==='aidan'){await frame.waitForFunction(()=>window.__game?.world,null,{polling:100});await frame.locator('#btn-play-keyboard').dispatchEvent('click');}await p.waitForTimeout(400);await p.waitForTimeout(700);await p.screenshot({path:path.join(H,'assets/baseline.png'),clip:{x:80,y:0,width:1100,height:820}});check('Existing baseline renders real canvas',await frame.locator('canvas').count()>0);check('Baseline startup has no JavaScript errors',errs.length===0,errs);check('Preview returns directly to this HUB',await p.locator('#home').getAttribute('href').then(x=>x.startsWith('../hub/')));report.baseline_rendering='Normal rendering loop used for startup/screenshot only; not a normal-path or performance test.';await c.close();}
const ctx=await browser.newContext({viewport:{width:1440,height:1000},hasTouch:true,reducedMotion:'reduce',acceptDownloads:true});ctx.setDefaultTimeout(15000);const p=await ctx.newPage(),errors=[],links=new Set();p.on('pageerror',e=>errors.push(e.message));
for(const language of ['zh-CN','en'])for(const page of ['index','rebuild','development','comparison','costs','guide','parents','review']){
 await p.goto(base+'hub/'+page+'.html?lang='+language+'&verify=preclass',{waitUntil:'domcontentloaded'});await p.waitForFunction(()=>window.__prepHub?.revision==='r6-preclass-20260926');
 const d=await p.evaluate(()=>({text:document.getElementById('app').innerText,wide:document.documentElement.scrollWidth>innerWidth+2,lang:document.documentElement.lang,button:document.getElementById('language')?.textContent,links:[...document.querySelectorAll('a[href],img[src],script[src],link[href]')].map(x=>x.href||x.src)}));d.links.forEach(x=>links.add(x));
 check(page+' '+language+' renders project content',!!await p.locator('h1').textContent()&&!/undefined|NaN|Infinity/.test(d.text));check(page+' '+language+' no wrong student or fake completion',!/(?:Joey|Martin|Naomi|Wildbound|Skyvale|6\/7|85\.7%)/.test(d.text),d.text.match(/(?:Joey|Martin|Naomi|Wildbound|Skyvale|6\/7|85\.7%)/)?.[0]);check(page+' '+language+' desktop fits',!d.wide);check(page+' '+language+' target-language toggle',d.button===(language==='en'?'中文':'English')&&d.lang===language);
 if(page==='index'){check('Two planned remakes visible',await p.locator('[data-status="planned"]').count()===2);check('No rating or game launch invented for planned candidates',await p.locator('[data-status="planned"] .ai-rating').count()===0&&await p.locator('[data-status="planned"] a[href*="/play/"]').count()===0);check('Four native R6 metrics retained',await p.locator('.project-dashboard .metric').count()===4);check('Three-stage plan and correct new-work progress',await p.locator('[data-phase]').count()===3&&await p.locator('[data-overall]').textContent()==='9.5%');check('Existing baseline separate from remakes',await p.evaluate(()=>document.getElementById('history').offsetTop>document.getElementById('builds').offsetTop));await p.locator('img').evaluateAll(xs=>xs.forEach(x=>x.loading='eager'));await p.waitForFunction(()=>[...document.images].every(i=>i.complete&&i.naturalWidth>0));if(language==='zh-CN')await p.screenshot({path:path.join(H,'qa',(live?'live-':'')+'hub-desktop.png'),fullPage:true,animations:'disabled'});}
 if(page==='comparison'){check('Only real baseline has AI review',await p.locator('[data-ai-review]').count()===1);}
 if(page==='rebuild'){check('Both task panels exist',await p.locator('[data-copy-task]').count()===2);await p.locator('[data-copy-task="opus"]').tap();await p.waitForFunction(()=>document.getElementById('task-opus').value.length>100);const text=await p.inputValue('#task-opus');check('Copy task uses correct project and execution gate',text.includes(repo)&&text.includes('Execute only after'));}
}
for(const width of [1024,768,390]){await p.setViewportSize({width,height:900});for(const page of ['index','rebuild','costs','review']){await p.goto(base+'hub/'+page+'.html?lang=zh-CN');await p.waitForFunction(()=>window.__prepHub);const wide=await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth+2);check(page+' fits '+width,!wide);await p.evaluate(()=>scrollTo(0,document.body.scrollHeight));const b=await p.locator('#language').boundingBox();check(page+' language visible after scroll '+width,b&&b.x>=0&&b.y>=0&&b.x+b.width<=width+2&&b.y+b.height<902);if(width===390&&page==='index')await p.screenshot({path:path.join(H,'qa',(live?'live-':'')+'hub-mobile-bottom.png'),animations:'disabled'});}}
await p.setViewportSize({width:1180,height:900});await p.goto(base+'hub/review.html?lang=zh-CN#draft');await p.waitForFunction(()=>window.__prepHub);const reviewer=P.people_names[0];await p.selectOption('#reviewer',reviewer);await p.fill('#device','iPad Safari QA');await p.fill('#notes','QA temporary draft: action -> expected -> actual');await p.locator('#language').tap();check('Language switch retains draft and reviewer',await p.inputValue('#notes')==='QA temporary draft: action -> expected -> actual'&&await p.inputValue('#reviewer')===reviewer&&await p.inputValue('#device')==='iPad Safari QA');check('Language switch retains page hash',p.url().endsWith('#draft'));await p.locator('#saveFeedback').click();const dl=p.waitForEvent('download');await p.locator('#exportFeedback').click();const d=await dl;const dest=path.join(H,'qa/.draft.json');await d.saveAs(dest);const draft=JSON.parse(fs.readFileSync(dest));check('Feedback JSON roundtrip',draft.reviewer===reviewer);fs.unlinkSync(dest);
const missing=[];for(const u of links){if(!u.startsWith(base))continue;const rel=new URL(u).pathname.slice(repo.length+2);if(rel.startsWith('downloads/'))continue;if(!fs.existsSync(path.join(site,rel)))missing.push(rel);}check('All local page/asset/diagram/task links exist',missing.length===0,missing);
const prep=JSON.parse(fs.readFileSync(path.join(H,'preparation.json'))),changed=Object.entries(prep.protected_game_files).filter(([file,hash])=>digest(fs.readFileSync(path.join(R,file)))!==hash).map(x=>x[0]);check('Original game files unchanged',changed.length===0,changed);const statuses=['opus','astra'].map(x=>JSON.parse(fs.readFileSync(path.join(site,'rebuild',x,'STATUS.json'))));check('Neither remake was executed or pre-rated',statuses.every(x=>x.status==='PLANNED_NOT_STARTED'&&x.play_url===null&&x.ai_rating===null));check('Budget forecast is sum, reservations not spend',P.cost.items.reduce((s,x)=>s+x.aud,0)===P.cost.api_equivalent_aud&&P.cost.planned_reserve===20&&P.cost.actual_metered_aud===null);
check('No HUB runtime exceptions',errors.length===0,errors);await ctx.close();
}catch(e){report.failures.push(String(e.message));}finally{if(browser)await browser.close();if(server){server.closeAllConnections?.();await new Promise(r=>server.close(r));}report.finished=new Date().toISOString();report.status=report.failures.length?'FAIL':'PASS';fs.writeFileSync(path.join(H,'qa',live?'live-results.json':'results.json'),JSON.stringify(report,null,2));console.log(JSON.stringify({project:P.id,status:report.status,checks:report.checks.length,failures:report.failures},null,2));if(report.failures.length)process.exitCode=1;}})();
